language: python

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

matrix:
  include:
    - python: 3.8
      env:
        TOXENV: py38

install: pip install --upgrade pip tox poetry

script:	tox